import type { Meta, StoryObj } from '@storybook/react';
import NetworkMapSection, {
  NetworkMapFilterItem,
  type NetworkMapSectionProps,
} from './NetworkMapSection';

import NetworkMapSprite from './NetworkMapSection';

const componentMeta: Meta<NetworkMapSectionProps> = {
  title: 'Layout/Network Map Section',
  component: NetworkMapSection,
  parameters: {
    layout: 'fullscreen',
  },
  subcomponents: {
    NetworkMapFilterItem,
    NetworkMapSprite,
  } as Record<string, React.ComponentType<unknown>>,
};

export default componentMeta;

type story = StoryObj<NetworkMapSectionProps>;

export const Default: story = {
  args: {
    id: 'global-coverage',
    heading: 'Explore our global coverage',
    copy: 'Filter by product families, services, and regions.',
    filters: {
      services: {
        communications: {
          select: {
            placeholder: 'Services',
            value: 'Inbound Calling',
            items: [
              {
                name: 'Inbound Calling',
                value: 'Inbound Calling',
              },
              {
                name: 'Local Calling',
                value: 'Local Calling',
              },
              {
                name: 'Emergency Calling',
                value: 'Emergency Calling',
              },
              {
                name: 'Fax support',
                value: 'Fax support',
              },
              {
                name: 'Number Portability',
                value: 'Number Portability',
              },
              {
                name: 'Two-way SMS',
                value: '2 Way Sms',
              },
              {
                name: 'Outbound SMS',
                value: 'Outbound Sms',
              },
              {
                name: 'Full PSTN Replacement',
                value: 'Full PSTN Replacement',
              },
              {
                name: 'Operator Connect',
                value: 'Operator Connect',
              },
            ],
          },
          enabledMap: {
            'Inbound Calling': {
              MX: ['Local', 'Toll-free numbers'],
              CO: ['Local', 'Toll-free', 'Mobile numbers'],
              JP: ['National', 'Toll-free numbers'],
              US: ['Local', 'Toll-free', 'Mobile numbers'],
              SG: ['Local', 'Toll-free', 'National', 'VoIP numbers'],
              PY: ['Local', 'Toll-free numbers'],
              AD: ['Local', 'Toll-free'],
              AE: ['Local', 'Toll-free'],
              AF: ['Local', 'Toll-free'],
              AG: ['Local', 'Toll-free'],
              AI: ['Local', 'Toll-free'],
              AL: ['Local', 'Toll-free'],
              AM: ['Local', 'Toll-free'],
              AR: ['Local', 'Toll-free'],
              AS: ['Local', 'Toll-free'],
              AT: ['Local', 'Toll-free'],
              AU: ['Local', 'Toll-free'],
              AW: ['Local', 'Toll-free'],
              AX: ['Local', 'Toll-free'],
              AZ: ['Local', 'Toll-free'],
              BA: ['Local', 'Toll-free'],
              BB: ['Local', 'Toll-free'],
              BD: ['Local', 'Toll-free'],
              BE: ['Local', 'Toll-free'],
              BF: ['Local', 'Toll-free'],
              BG: ['Local', 'Toll-free'],
              BH: ['Local', 'Toll-free'],
              BI: ['Local', 'Toll-free'],
              BJ: ['Local', 'Toll-free'],
              BL: ['Local', 'Toll-free'],
              BN: ['Local', 'Toll-free'],
              BO: ['Local', 'Toll-free'],
              BM: ['Local', 'Toll-free'],
              BQ: ['Local', 'Toll-free'],
              BR: ['Local', 'Toll-free'],
              BS: ['Local', 'Toll-free'],
              BT: ['Local', 'Toll-free'],
              BV: ['Local', 'Toll-free'],
              BW: ['Local', 'Toll-free'],
              BY: ['Local', 'Toll-free'],
              BZ: ['Local', 'Toll-free'],
              CA: ['Local', 'Toll-free'],
              CC: ['Local', 'Toll-free'],
              CG: ['Local', 'Toll-free'],
              CH: ['Local', 'Toll-free'],
              CI: ['Local', 'Toll-free'],
              CK: ['Local', 'Toll-free'],
              CL: ['Local', 'Toll-free'],
              CM: ['Local', 'Toll-free'],
              CN: ['Local', 'Toll-free'],
              CR: ['Local', 'Toll-free'],
              CV: ['Local', 'Toll-free'],
              CW: ['Local', 'Toll-free'],
              CX: ['Local', 'Toll-free'],
              CY: ['Local', 'Toll-free'],
              CZ: ['Local', 'Toll-free'],
              DE: ['Local', 'Toll-free'],
              DJ: ['Local', 'Toll-free'],
              DK: ['Local', 'Toll-free'],
              DM: ['Local', 'Toll-free'],
              DO: ['Local', 'Toll-free'],
              DZ: ['Local', 'Toll-free'],
              EC: ['Local', 'Toll-free'],
              EG: ['Local', 'Toll-free'],
              EE: ['Local', 'Toll-free'],
              EH: ['Local', 'Toll-free'],
              ER: ['Local', 'Toll-free'],
              ES: ['Local', 'Toll-free'],
              ET: ['Local', 'Toll-free'],
              FI: ['Local', 'Toll-free'],
              FJ: ['Local', 'Toll-free'],
              FK: ['Local', 'Toll-free'],
              FM: ['Local', 'Toll-free'],
              FO: ['Local', 'Toll-free'],
              FR: ['Local', 'Toll-free'],
              GA: ['Local', 'Toll-free'],
              GB: ['Local', 'Toll-free'],
              GE: ['Local', 'Toll-free'],
              GD: ['Local', 'Toll-free'],
              GF: ['Local', 'Toll-free'],
              GG: ['Local', 'Toll-free'],
              GH: ['Local', 'Toll-free'],
              GI: ['Local', 'Toll-free'],
              GM: ['Local', 'Toll-free'],
              GN: ['Local', 'Toll-free'],
              GP: ['Local', 'Toll-free'],
              GQ: ['Local', 'Toll-free'],
              GR: ['Local', 'Toll-free'],
              GS: ['Local', 'Toll-free'],
              GT: ['Local', 'Toll-free'],
              GU: ['Local', 'Toll-free'],
              GW: ['Local', 'Toll-free'],
              GY: ['Local', 'Toll-free'],
              HK: ['Local', 'Toll-free'],
              HM: ['Local', 'Toll-free'],
              HN: ['Local', 'Toll-free'],
              HR: ['Local', 'Toll-free'],
              HT: ['Local', 'Toll-free'],
              HU: ['Local', 'Toll-free'],
              ID: ['Local', 'Toll-free'],
              IE: ['Local', 'Toll-free'],
              IL: ['Local', 'Toll-free'],
              IM: ['Local', 'Toll-free'],
              IN: ['Local', 'Toll-free'],
              IO: ['Local', 'Toll-free'],
              IQ: ['Local', 'Toll-free'],
              IS: ['Local', 'Toll-free'],
              IT: ['Local', 'Toll-free'],
              JE: ['Local', 'Toll-free'],
              JM: ['Local', 'Toll-free'],
              JO: ['Local', 'Toll-free'],
              KE: ['Local', 'Toll-free'],
              KG: ['Local', 'Toll-free'],
              KH: ['Local', 'Toll-free'],
              KI: ['Local', 'Toll-free'],
              KM: ['Local', 'Toll-free'],
              KN: ['Local', 'Toll-free'],
              KP: ['Local', 'Toll-free'],
              KR: ['Local', 'Toll-free'],
              XK: ['Local', 'Toll-free'],
              KW: ['Local', 'Toll-free'],
              KY: ['Local', 'Toll-free'],
              KZ: ['Local', 'Toll-free'],
              LA: ['Local', 'Toll-free'],
              LB: ['Local', 'Toll-free'],
              LC: ['Local', 'Toll-free'],
              LI: ['Local', 'Toll-free'],
              LK: ['Local', 'Toll-free'],
              LR: ['Local', 'Toll-free'],
              LS: ['Local', 'Toll-free'],
              LT: ['Local', 'Toll-free'],
              LU: ['Local', 'Toll-free'],
              LV: ['Local', 'Toll-free'],
              LY: ['Local', 'Toll-free'],
              MA: ['Local', 'Toll-free'],
              MC: ['Local', 'Toll-free'],
              MD: ['Local', 'Toll-free'],
              MF: ['Local', 'Toll-free'],
              MH: ['Local', 'Toll-free'],
              ML: ['Local', 'Toll-free'],
              MO: ['Local', 'Toll-free'],
              MM: ['Local', 'Toll-free'],
              MN: ['Local', 'Toll-free'],
              MP: ['Local', 'Toll-free'],
              MQ: ['Local', 'Toll-free'],
              MR: ['Local', 'Toll-free'],
              MS: ['Local', 'Toll-free'],
              MT: ['Local', 'Toll-free'],
              MU: ['Local', 'Toll-free'],
              MV: ['Local', 'Toll-free'],
              MW: ['Local', 'Toll-free'],
              MY: ['Local', 'Toll-free'],
              MZ: ['Local', 'Toll-free'],
              NC: ['Local', 'Toll-free'],
              NF: ['Local', 'Toll-free'],
              NG: ['Local', 'Toll-free'],
              NL: ['Local', 'Toll-free'],
              NO: ['Local', 'Toll-free'],
              NP: ['Local', 'Toll-free'],
              NR: ['Local', 'Toll-free'],
              NU: ['Local', 'Toll-free'],
              NZ: ['Local', 'Toll-free'],
              OM: ['Local', 'Toll-free'],
              PA: ['Local', 'Toll-free'],
              PE: ['Local', 'Toll-free'],
              PF: ['Local', 'Toll-free'],
              PG: ['Local', 'Toll-free'],
              PH: ['Local', 'Toll-free'],
              PK: ['Local', 'Toll-free'],
              PL: ['Local', 'Toll-free'],
              PM: ['Local', 'Toll-free'],
              PN: ['Local', 'Toll-free'],
              PR: ['Local', 'Toll-free'],
              PS: ['Local', 'Toll-free'],
              PT: ['Local', 'Toll-free'],
              PW: ['Local', 'Toll-free'],
              QA: ['Local', 'Toll-free'],
              RE: ['Local', 'Toll-free'],
              RO: ['Local', 'Toll-free'],
              RS: ['Local', 'Toll-free'],
              RW: ['Local', 'Toll-free'],
              SA: ['Local', 'Toll-free'],
              SB: ['Local', 'Toll-free'],
              SC: ['Local', 'Toll-free'],
              SE: ['Local', 'Toll-free'],
              SH: ['Local', 'Toll-free'],
              SI: ['Local', 'Toll-free'],
              SJ: ['Local', 'Toll-free'],
              SK: ['Local', 'Toll-free'],
              SL: ['Local', 'Toll-free'],
              SM: ['Local', 'Toll-free'],
              SS: ['Local', 'Toll-free'],
              ST: ['Local', 'Toll-free'],
              SV: ['Local', 'Toll-free'],
              SX: ['Local', 'Toll-free'],
              SY: ['Local', 'Toll-free'],
              SZ: ['Local', 'Toll-free'],
              TC: ['Local', 'Toll-free'],
              TF: ['Local', 'Toll-free'],
              TH: ['Local', 'Toll-free'],
              TJ: ['Local', 'Toll-free'],
              TK: ['Local', 'Toll-free'],
              TL: ['Local', 'Toll-free'],
              TO: ['Local', 'Toll-free'],
              TR: ['Local', 'Toll-free'],
              TT: ['Local', 'Toll-free'],
              TV: ['Local', 'Toll-free'],
              TW: ['Local', 'Toll-free'],
              TZ: ['Local', 'Toll-free'],
              UA: ['Local', 'Toll-free'],
              UG: ['Local', 'Toll-free'],
              'UM-DQ': ['Local', 'Toll-free'],
              'UM-FQ': ['Local', 'Toll-free'],
              'UM-HQ': ['Local', 'Toll-free'],
              'UM-JQ': ['Local', 'Toll-free'],
              'UM-MQ': ['Local', 'Toll-free'],
              'UM-WQ': ['Local', 'Toll-free'],
              VA: ['Local', 'Toll-free'],
              VC: ['Local', 'Toll-free'],
              VE: ['Local', 'Toll-free'],
              VG: ['Local', 'Toll-free'],
              VI: ['Local', 'Toll-free'],
              VN: ['Local', 'Toll-free'],
              VU: ['Local', 'Toll-free'],
              WF: ['Local', 'Toll-free'],
              WS: ['Local', 'Toll-free'],
              YE: ['Local', 'Toll-free'],
              YT: ['Local', 'Toll-free'],
              ZA: ['Local', 'Toll-free'],
            },
            'Local Calling': { BR: ['Local'], US: ['Local'] },
            'Emergency Calling': {},
            'Fax support': {},
            'Number Portability': {},
            '2 Way Sms': {},
            'Full PSTN Replacement': {},
            'Operator Connect': {},
          },
        },
        iot: {
          select: {
            placeholder: 'Services',
            value: '5G',
            items: [
              {
                name: '5G',
                value: '5G',
              },
              {
                name: '4G (LTE)',
                value: '4G (LTE)',
              },
              {
                name: '3G',
                value: '3G',
              },
              {
                name: 'LTE-M',
                value: 'LTE-M',
              },
              {
                name: 'NB-IoT',
                value: 'NB-IoT',
              },
            ],
          },
          enabledMap: {
            '5G': {
              BG: ['A1 Bulgaria', 'Yettel Bulgaria EAD'],
              CA: [
                'Bell Mobility Inc.',
                'Videotron',
                'Rogers Communications Canada Inc.',
              ],
            },
            '4G (LTE)': {
              CN: [
                'CHINA MOBILE COMMUNICATION CORPORATION',
                'CHINA UNICOM CORPORATION LTD',
              ],
            },
            '3G': {
              AR: ['TELECOM PERSONAL SA', 'TELEFÓNICA MOVILES ARGENTINA S.A'],
              BR: [
                'BRASIL TELECOM CELLULAR SA',
                'CLARO SA ("BRAZIL TELECOM CELLULAR")',
                'TIM BRASIL SAO PAULO',
                'TNL PCS',
                'VIVO',
              ],
              CN: [
                'CHINA MOBILE COMMUNICATION CORPORATION',
                'CHINA UNICOM CORPORATION LTD',
              ],
              IN: [
                'AIRCEL',
                'Airtel Assam',
                'Airtel Bihar',
                'Airtel North East',
                'Airtel Orissa',
                'Airtel UP East',
                'Airtel West Bengal',
                'BHARTI AIRTEL Ltd (New Delhi)',
                'BHARTI TELE-VENTURES',
                'BSNL',
                'ESCOTEL - HARYANA',
                'HEXACOM INDIA LTD',
                'IDEA CELLULAR (Andhra Pradesh)',
                'IDEA GUJARAT',
                'IDEA MAHARASTRA',
                'LOOP MOBILE',
                'MTNL MUMBAI',
                'Reliance Jio Infocomm Limited',
                'RELIANCE TELECOM LIMITED',
                'SPICE TELE KARNATAKA',
                'SPICE TELECOM PUNJAB',
                'TATA DOCOMO INDIA (MAHARASHTRA&GOA)',
                'VODAFONE E. G.',
                'VODAFONE EAST LIMIT.',
                'VODAFONE ESSAR LIM',
                'Vodafone Idea Limited (ex Vodafone Essar South limited - Punjab-',
                'Vodafone Idea Limited (ex Vodafone Essar South limited -West Bengala-',
                'Vodafone Idea Limited (exOrange ex Aircel Digilink India Limited - Huchinson Essar Haryana)',
                'Vodafone Idea Limited ex Vodafone Essar South limited -Uttar Pradesh West-',
                'VODAFONE MOBILE',
              ],
              US: [
                'AT&T',
                'CHOICE WIRELESS L.C.',
                'Commnet',
                'GCI WIRELESS',
                'KEYSTONE WIRELESS',
                'PULSE',
                'SUNCOM PCS',
                'T-MOBILE USA',
                'TELNA MOBILE',
                'UNION TELEPHONE CMP',
                'UNION WIRELESS',
                'US Cellular',
                'Verizon Wireless',
                'VIAERO WIRELESS',
                'VIYA',
                'WSI',
              ],
              UY: [
                "AM Wireless Uruguay S.A. 'CLARO' (ex-CTI MOVIL)",
                'ANTEL',
                'TELEFONICA MOVILES DE URUGUAY',
              ],
            },
            'LTE-M': {},
            'NB-IoT': {},
          },
        },
        networking: {
          select: {
            placeholder: 'Services',
            value: 'Telephony',
            items: [
              {
                name: 'Telephony',
                value: 'Telephony',
              },
              {
                name: 'Storage',
                value: 'Storage',
              },
              {
                name: 'VXC',
                value: 'VXC',
              },
              {
                name: 'Cloud VPN',
                value: 'Cloud VPN',
              },
              {
                name: 'Global Edge Router',
                value: 'Global Edge Router',
              },
            ],
          },
          enabledMap: {
            Telephony: {
              AU: ['Core PoP'],
              DE: ['Core PoP'],
              CA: ['Core PoP'],
              NL: ['Core PoP'],
              SG: ['Core PoP'],
              US: ['Core PoP', 'Edge Site'],
              GB: ['Core PoP'],
            },
            Storage: {
              AU: ['Core PoP'],
              DE: ['Core PoP'],
              CA: ['Core PoP'],
              NL: ['Core PoP'],
              SG: ['Core PoP'],
              US: ['Core PoP', 'Edge Site'],
              GB: ['Core PoP'],
            },
            'Cloud VPN': {
              AU: ['Core PoP'],
              DE: ['Core PoP'],
              CA: ['Core PoP'],
              NL: ['Core PoP'],
              SG: ['Core PoP'],
              US: ['Core PoP'],
              GB: ['Core PoP'],
            },
            VXC: {
              AU: ['Core PoP'],
              DE: ['Core PoP'],
              CA: ['Core PoP'],
              NL: ['Core PoP'],
              SG: ['Core PoP'],
              US: ['Core PoP'],
              GB: ['Core PoP'],
            },
            'Global Edge Router': {
              AU: ['Bare Metal PoP'],
              DE: ['Bare Metal PoP'],
              CA: ['Bare Metal PoP'],
              NL: ['Bare Metal PoP'],
              SG: ['Bare Metal PoP'],
              US: ['Bare Metal PoP'],
              GB: ['Bare Metal PoP'],
            },
          },
        },
        compute: {
          select: {
            placeholder: 'Services',
            value: 'Cloud storage',
            items: [
              {
                name: 'AI',
                value: 'AI',
              },
              {
                name: 'Cloud storage',
                value: 'Cloud storage',
              },
            ],
          },
          enabledMap: {
            'Cloud storage': {
              US: ['Telnyx Bare Metal'],
            },
            AI: {
              US: ['Telnyx Bare Metal'],
            },
          },
        },
      },
      cta: {
        communications: {
          href: '/global-coverage',
          text: 'View full coverage',
          type: 'link',
          linkKind: 'cta',
        },
        iot: {
          href: '/iot-global-coverage',
          text: 'View full coverage',
          type: 'link',
          linkKind: 'cta',
        },
      },
    },
    backgroundColor: 'blue',
    transparent: false,
  },
};
