//#region Build Configuration
export const OUTPUT_STATIC = String(process.env.NEXT_PUBLIC_OUTPUT_STATIC || 'false');
export const DISABLE_IN_MEMORY_CACHE = String(process.env.DISABLE_IN_MEMORY_CACHE) === 'true';
export const ENABLE_STRAPI_AUTOGENERATED_TYPES = Boolean(process.env.STRAPI_GITHUB_REPO_TOKEN);

export const REDIRECTS_ENTRY = 'QqN4NPu7kNIkNfThCJxZa';

// necessary cause `import { PHASE_PRODUCTION_BUILD, ... } from 'next/constants' fails for this .mjs file
export const PHASE_PRODUCTION_BUILD = 'phase-production-build';
export const PHASE_DEVELOPMENT_SERVER = 'phase-development-server';
export const locales = ['en-US'];
export const defaultLocale = 'en-US';
// end necessary -------------------------------->
