const constants = {
  BLOG_POSTS_RELATED_ARTICLES_MINIMUM: 5,
  BLOG_POSTS_RELATED_ARTICLES_LIMIT: 30,

  MAX_BLOG_POSTS_PER_PAGE: 30,
  MAX_PRE_GENERATED_BLOG_POSTS_PAGES: 4,
  SOLUTIONS_PAGE_LOAD: 4,
  RELEASE_NOTES_PAGE_LIMIT: 12,
  PAGES_MINIMUM_LIMIT: 100,
  PAGES_MAXIMUM_LIMIT: 1000,
  SOLUTIONS_USE_CASES_PAGE_LIMIT: 6,
};
export default constants;
